app/views/event/participations/_asides_insieme.html.haml
app/views/people/_reference_person_number.html.haml

Migrate FontAwesome to version 5

---

app/domain/vp2015/time_record/calculation.rb
app/domain/vp2020/time_record/calculation.rb
app/helpers/insieme/standard_form_builder.rb
app/helpers/vertragsperioden_helper.rb
app/models/time_record.rb
app/views/vp2020/time_records/_lufeb_fields_full.html.haml
app/views/vp2020/time_records/_lufeb_fields_sumarized.html.haml
app/views/vp2020/time_records/edit.html.haml
config/locales/models.insieme.de.yml
config/locales/views.insieme.de.yml
db/migrate/20200518064100_add_more_2020_fields_to_time_records.rb
lib/hitobito_insieme/wagon.rb
spec/vp2020/domain/time_record/calculation_spec.rb
spec/vp2020/models/time_record_spec.rb

Einarbeitung Kundenfeedback

---

.travis.yml
app/controllers/event/course_records_controller.rb
app/controllers/insieme/events_controller.rb
app/domain/course_reporting/aggregation.rb
app/domain/statistics/group_figures.rb
app/domain/vertragsperioden/domain.rb
app/domain/vp2015/event/course_record/calculation.rb
app/domain/vp2015/time_record/calculation.rb
app/domain/vp2020/event/course_record/calculation.rb
app/domain/vp2020/time_record/calculation.rb
app/helpers/insieme/standard_form_builder.rb
app/helpers/vertragsperioden_helper.rb
app/models/event/course_record.rb
app/models/event/reportable.rb
app/models/insieme/event/course.rb
app/models/time_record.rb
app/views/vp2020/event/course_records/_evaluation_fields.html.haml
app/views/vp2020/event/course_records/_main_fields.html.haml
app/views/vp2020/time_records/_lufeb_fields_full.html.haml
app/views/vp2020/time_records/_lufeb_fields_sumarized.html.haml
app/views/vp2020/time_records/edit.html.haml
config/locales/models.insieme.de.yml
config/locales/models.insieme.fr.yml
config/locales/views.insieme.de.yml
db/migrate/20200518064100_add_more_2020_fields_to_time_records.rb
lib/hitobito_insieme/wagon.rb
spec/domain/course_reporting/aggregation_spec.rb
spec/vp2020/domain/time_record/calculation_spec.rb
spec/vp2020/models/event/course_record_spec.rb
spec/vp2020/models/time_record_spec.rb

Vp2020 fields course record

---

app/controllers/reporting_parameters_controller.rb
app/domain/vp2015/time_record/report/base.rb
app/domain/vp2020/time_record/report/base.rb
app/domain/vp2020/time_record/report/capital_substrate_limit.rb
app/views/reporting_parameters/_form.html.haml
config/locales/models.insieme.de.yml
db/migrate/20200617134800_add_capital_substrate_limit_to_reporting_parameters.rb
db/seeds/reporting_parameters.rb
spec/fixtures/reporting_parameters.yml
spec/models/reporting_parameter_spec.rb
spec/regressions/reporting_parameters_controller_spec.rb
spec/support/reload_column_information.rb
spec/vp2020/domain/time_record/report/capital_substrate_limit_spec.rb

neuer Reportingparameter "Kapitalsubstrat Limit"

---

app/controllers/course_reporting/aggregations_controller.rb
app/domain/vertragsperioden/domain.rb
app/domain/vp2015/course_reporting/aggregation.rb
app/domain/vp2015/export/tabular/course_reporting/aggregation.rb
app/domain/vp2020/course_reporting/aggregation.rb
app/domain/vp2020/export/tabular/course_reporting/aggregation.rb
app/models/event/reportable.rb
app/views/vp2020/course_reporting/aggregations/index.html.haml
config/locales/views.insieme.de.yml
spec/vp2015/domain/course_reporting/aggregation_spec.rb
spec/vp2015/domain/export/tabular/course_reporting/aggregation_spec.rb
spec/vp2020/domain/course_reporting/aggregation_spec.rb
spec/vp2020/domain/export/tabular/course_reporting/aggregation_spec.rb

Course aggregation exports

---

app/domain/vp2020/time_record/report/capital_substrate.rb
app/models/capital_substrate.rb
app/models/reporting_parameter.rb
app/views/vp2020/capital_substrate/edit.html.haml
config/locales/models.insieme.de.yml
config/locales/views.insieme.de.yml
db/migrate/20200627120000_add_earmarked_funds_to_capital_substrates.rb
spec/vp2020/domain/time_record/report/capital_substrate_spec.rb

Adapt capital substrate form and calculation for VP2020

---

app/domain/vp2020/cost_accounting/report/honorare.rb
app/domain/vp2020/cost_accounting/report/raumaufwand.rb
app/domain/vp2020/cost_accounting/report/uebriger_sachaufwand.rb
app/helpers/cost_accounting_helper.rb
app/views/vp2020/cost_accounting/edit.html.haml

Display the previously hidden inputs explicitly as readonly in the edit form

---

app/controllers/insieme/event/participations_controller.rb
app/controllers/insieme/people_controller.rb
app/models/insieme/person.rb
app/views/event/participation_contact_datas/_fields_insieme.html.haml
app/views/event/participations/_fields_insieme.html.haml
app/views/roles/_additional_person_fields_insieme.html.haml
spec/controllers/event/register_controller_spec.rb

Anpassungen der Personen-Validierungen

---

app/domain/vp2020/time_record/report/capital_substrate.rb
app/models/capital_substrate.rb
app/views/capital_substrate/edit.html.haml
spec/vp2020/domain/export/tabular/statistics/group_figures_spec.rb
spec/vp2020/domain/time_record/report/capital_substrate_spec.rb

Remove fund-building from capital-subtrate calculation

---

.rubocop.yml
app/domain/vp2020/course_reporting/client_statistics.rb
app/domain/vp2020/export/tabular/course_reporting/client_statistics.rb
config/locales/views.insieme.de.yml
spec/vp2020/domain/course_reporting/client_statistics_spec.rb
spec/vp2020/domain/export/tabular/course_reporting/client_statistics_spec.rb

Anpassungen Controlling/KlientInnen-Statistik

---

app/assets/stylesheets/hitobito/customizable/_wagon.scss

Merge together with hitobito/hitobito#1031

Adjustments for webpacker

---

spec/fixtures/event_translations.yml
spec/fixtures/events.yml

Can and should be merged once https://github.com/hitobito/hitobito/pull/1135 is merged.

Adapt fixtures to event-translation

---

app/domain/vp2020/export/tabular/statistics/group_figures.rb
app/domain/vp2020/statistics/group_figures.rb
config/locales/views.insieme.de.yml
spec/vp2020/domain/course_reporting/client_statistics_spec.rb
spec/vp2020/domain/export/tabular/statistics/group_figures_spec.rb

Betreuungsstunden in Export

---

spec/controllers/events_controller_spec.rb

Basically:
- Adapt to new error-API, resolving deprecation
See hitobito/hitobito#1390, hitobito/hitobito#1400

Rails 6.1 for the wagon

---

CHANGELOG.md
app/domain/vp2020/export/tabular/statistics/group_figures.rb
config/locales/views.insieme.de.yml
spec/vp2020/domain/export/tabular/statistics/group_figures_spec.rb

Extend export with 3 more fields

---

app/domain/vp2020/course_reporting/client_statistics.rb
spec/vp2020/domain/export/tabular/course_reporting/client_statistics_spec.rb

Correctly substract absences in export

---

app/domain/vp2020/time_record/report/capital_substrate.rb
spec/vp2020/domain/time_record/report/capital_substrate_spec.rb

Set upper bound for summed up capital substrate

---

app/models/event/aggregate_course.rb
app/views/events/_date_fields.html.haml
app/views/events/_form_tabs.html.haml
lib/hitobito_insieme.rb

See hitobito/hitobito#1594
Fixes https://sentry.puzzle.ch/pitc/hitobito-backend/issues/46088

Avoid `render file: abs_path`, use core-customization

---

app/assets/stylesheets/hitobito/customizable/_wagon.scss

Can be merged before https://github.com/hitobito/hitobito/pull/1634, must be merged after.

Drop Compass

---

app/domain/vp2020/time_record/report/capital_substrate.rb
app/views/vp2020/capital_substrate/edit.html.haml
config/locales/models.insieme.de.yml
config/locales/views.insieme.de.yml
spec/vp2020/domain/time_record/report/capital_substrate_spec.rb

Anpassungen für IV Finanzierungsgrad

---

spec/helpers/event/course_records_helper_spec.rb

refs #132
depends on hitobito/hitobito#1934

Spec for course records inline help format rendering

---

README.md
app/models/group/aktivmitglieder.rb
app/models/group/dachverein.rb
app/models/group/dachverein_abonnemente.rb
app/models/group/dachverein_gremium.rb
app/models/group/dachverein_liste.rb
app/models/group/externe_organisation.rb
app/models/group/externe_organisation_gremium.rb
app/models/group/externe_organisation_liste.rb
app/models/group/kollektivmitglieder.rb
app/models/group/passivmitglieder.rb
app/models/group/regionalverein.rb
app/models/group/regionalverein_gremium.rb
app/models/group/regionalverein_liste.rb
spec/models/role_spec.rb

Enforce 2nd factor authentication

---

app/domain/insieme/export/pdf/invoice/invoice_information.rb
app/domain/insieme/person/address.rb
app/models/insieme/person.rb
config/locales/views.insieme.de.yml
lib/hitobito_insieme/wagon.rb
spec/controllers/invoices_controller_spec.rb
spec/domain/export/pdf/invoice_spec.rb

Fixes #133
Merge after hitobito/hitobito#1945

Dynamic invoice address

---

app/domain/fp2022/export/tabular/statistics/group_figures.rb
app/domain/fp2022/time_record/organisations_daten.rb
config/locales/views.insieme.de.yml
spec/domain/fp2022/export/tabular/statistics/group_figures_spec.rb
spec/domain/fp2022/export/tabular/time_records/organisations_daten_spec.rb
spec/domain/fp2022/time_record/organisations_daten_spec.rb

Anpassungen an Weiterentwicklungen

---

app/helpers/contactable_insieme_helper.rb
app/views/contactable/_additional_email_fields.html.haml
app/views/contactable/_phone_number_fields.html.haml

Depends on:  [2668](https://github.com/hitobito/hitobito/issues/2668)

fix additional fields styles

---

.gitignore
app/domain/insieme/import/person_duplicate_finder.rb

PEOPLE: Duplicate Finder Memory Usage (hitobito/hitobito#2824)

---

doc/adressen.md

Document custom addresses feature

---

.patches.yml
app/controllers/insieme/event/participations_controller.rb
app/domain/course_reporting/course_numbers.rb
app/models/event/aggregate_course.rb
app/models/insieme/event/participation.rb
app/views/event/participations/_fields_insieme.html.haml
spec/abilities/event/course_record_ability_spec.rb
spec/controllers/event/course_records_controller_spec.rb
spec/controllers/event/participations_controller_spec.rb
spec/domain/course_reporting/course_numbers_spec.rb
spec/domain/export/tabular/people/participations_full_spec.rb
spec/fixtures/event/participations.yml

Refs hitobito/hitobito_sww#208

Event guest adjustments
